# Generated by Django 2.2.6 on 2019-10-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(default='null', max_length=255)),
                ('bathrooms', models.CharField(default='null', max_length=255)),
                ('bedrooms', models.CharField(default='null', max_length=255)),
                ('home_size', models.CharField(default='null', max_length=255)),
                ('home_type', models.CharField(default='null', max_length=255)),
                ('last_sold_date', models.CharField(default='null', max_length=255)),
                ('last_sold_price', models.CharField(default='null', max_length=255)),
                ('link', models.CharField(default='null', max_length=255)),
                ('price', models.CharField(default='null', max_length=255)),
                ('property_size', models.CharField(default='null', max_length=255)),
                ('rent_price', models.CharField(default='null', max_length=255)),
                ('rentzestimate_amount', models.CharField(default='null', max_length=255)),
                ('rentzestimate_last_updated', models.CharField(default='null', max_length=255)),
                ('tax_value', models.CharField(default='null', max_length=255)),
                ('tax_year', models.CharField(default='null', max_length=255)),
                ('year_built', models.CharField(default='null', max_length=255)),
                ('zestimate_amount', models.CharField(default='null', max_length=255)),
                ('zestimate_last_updated', models.CharField(default='null', max_length=255)),
                ('zillow_id', models.CharField(default='null', max_length=255)),
                ('address', models.CharField(default='null', max_length=255)),
                ('city', models.CharField(default='null', max_length=255)),
                ('state', models.CharField(default='null', max_length=255)),
                ('zipcode', models.CharField(default='null', max_length=255)),
            ],
        ),
    ]
